title: gLabels.org
description: Design and print labels and business cards
theme: just-the-docs

url: https://j-evins.github.io/tmp-glabels.org

# Keep site simple for now
nav_enabled: true
search_enabled: true

footer_content: "&copy; 2025 Jaye Evins"
